version: '3'
services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        app_name: "realworld"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
